version: '2'

# docker-compose base layer
#
# This config is not sufficient by itself; it's just the base layer.
# For full config, see also docker-compose.{dev,prod}.yaml

services:
  nginx:
    build: ../nginx
    links:
      - hugo
      - kansa
      - raami
    entrypoint: /bin/bash -c "envsubst '$$SERVER_NAME $$SSL_CERTIFICATE $$SSL_CERTIFICATE_KEY' < /nginx.conf.template > /usr/local/openresty/nginx/conf/nginx.conf && /usr/local/openresty/bin/openresty -g 'daemon off;'"

  hugo:
    build: ../hugo
    expose:
      - "80"
    volumes:
      - ../config/kansa.yaml:/kansa.yaml:ro

  kansa:
    build: ../kansa
    links:
      - kyyhky
      - tarra
      - tuohi
    expose:
      - "80"
    volumes:
      - ../config/kansa.yaml:/kansa.yaml:ro
      - ../config/siteselection/ballot-data.js:/ss-ballot-data.js:ro

  raami:
    build: ../raami
    expose:
      - "3000"
    volumes:
      - ../config/kansa.yaml:/kansa.yaml:ro

  tarra:
    image: worldcon75devops/label-printer:0.3.0
    expose:
      - "80"

  tuohi:
    image: eeemeli/pdf-form-fill:0.2
    expose:
      - "3000"
    environment:
      PDF_TEMPLATE_DIR: /templates
    volumes:
      - ../config/siteselection/ballot.pdf:/templates/ss-ballot.pdf:ro

  kyyhky:
    build: ../kyyhky
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    expose:
      - "80"
    volumes:
      - ../config/message-templates:/message-templates:ro

  redis:
    image: redis:4.0
    expose:
      - "6379"
